### PR TITLE
Improve support for MoC cards

### PR DESCRIPTION
**Pull request by electricbrass**
I wanted to use this with the new MoC cards. I saw that they had been added but that no new release had been made yet, so I decided to just compile myself. I encountered a number of issues that prevent it from compiling and then from working properly once compiled so I did my best to fix everything I could. I've never done any .NET stuff before so hopefully this is all good.

I did not get the chaos events for c257 and c267 implemented.

### CODE REVIEW

**Comment by usulrasolas** [comment]
Thanks so much for the PR, my life is crazy and I haven't been able to devote any coding time to personal projects so this is greatly appreciated. I will set aside time soon to test and add this commit! Thank you so much for picking up my slack!

**Comment by electricbrass** [comment]
Happy to help. I might take a look at getting those chaos effects working this week too.

**Comment by electricbrass** [comment]
I'm looking at getting the chaos effects working and I have a question. For the event types, is there a particular pattern to the numbers used? Is there a reason for starting at 5 and skipping 8 and 10?
`CardStack(0, 4, 3) = 5 ''Aeropolis Flag for 10 Counters Walks Away`
`CardStack(0, 0, 3) = 7 ''Mount Keralia Damage on Exit Reminder/Reset`
`CardStack(0, 43, 3) = 6 ''Naar Isle Counter Reset on Exit`
`CardStack(0, 53, 3) = 9 ''Pools of Becoming Triple Draw Chaos`
`CardStack(0, 65, 3) = 11 ''Stairs to Infinity Scry Planar Deck Chaos`

**Comment by electricbrass** [comment]
Implemented 257 but it looks like 267 will take a lot more work because it allows the players to be on an arbitrary number of planes at once.

**Review by Razielous — APPROVED** [review]

**Comment by Razielous** [comment]
Everything looks good to me. Thank you for your contributions.

**Comment by usulrasolas** [comment]
> I'm looking at getting the chaos effects working and I have a question. For the event types, is there a particular pattern to the numbers used? Is there a reason for starting at 5 and skipping 8 and 10? `CardStack(0, 4, 3) = 5 ''Aeropolis Flag for 10 Counters Walks Away` `CardStack(0, 0, 3) = 7 ''Mount Keralia Damage on Exit Reminder/Reset` `CardStack(0, 43, 3) = 6 ''Naar Isle Counter Reset on Exit` `CardStack(0, 53, 3) = 9 ''Pools of Becoming Triple Draw Chaos` `CardStack(0, 65, 3) = 11 ''Stairs to Infinity Scry Planar Deck Chaos`

so this is an artifact of original number scheme, and should be considered basically arbitrary at this point

**Pull request merged**
